version: "3.8"

services: 

    configserver:
        image: bloodseeker/configserver:latest
        mem_limit: 700m
        ports: 
            - "8071:8071"
        networks: 
            - bloodseeker-network

    eurekaserver:
        image: bloodseeker/eurekaserver:latest
        mem_limit: 700m
        ports: 
            - "8070:8070"
        networks: 
            - bloodseeker-network
        depends_on: 
            - configserver
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        environment: 
            SPRING_PROFILES_ACTIVE: prod
            SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/ 


    accounts:
        image: bloodseeker/accounts:latest
        mem_limit: 700m
        ports: 
            - "8080:8080"
        networks: 
            - bloodseeker-network
        depends_on: 
            - configserver
            - eurekaserver
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        environment: 
            SPRING_PROFILES_ACTIVE: prod
            SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    
    loans:
        image: bloodseeker/loans:latest
        mem_limit: 700m
        ports:
            - "8090:8090"
        networks: 
            - bloodseeker-network
        depends_on: 
            - configserver
            - eurekaserver
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        environment: 
            SPRING_PROFILES_ACTIVE: prod
            SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    
    cards:
        image: bloodseeker/cards:latest
        mem_limit: 700m
        ports: 
            - "9000:9000"
        networks: 
            - bloodseeker-network
        depends_on: 
            - configserver
            - eurekaserver
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        environment: 
            SPRING_PROFILES_ACTIVE: prod
            SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

    gatewayserver:
        image: bloodseeker/gatewayserver:latest
        mem_limit: 700m
        ports: 
            - "8072:8072"
        networks: 
            - bloodseeker-network
        depends_on: 
            - configserver
            - eurekaserver
            - cards
            - loans
            - accounts
        deploy:
            restart_policy:
                condition: on-failure
                delay: 45s
                max_attempts: 3
                window: 180s
        environment: 
            SPRING_PROFILES_ACTIVE: prod
            SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

networks: 
    bloodseeker-network: